//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carretilla_Angular.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarretillaEntities : DbContext
    {
        public CarretillaEntities()
            : base("name=CarretillaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Carretilla> Carretilla { get; set; }
        public DbSet<categoriaProducto> categoriaProducto { get; set; }
        public DbSet<detalleCarretilla> detalleCarretilla { get; set; }
        public DbSet<Producto> Producto { get; set; }
    }
}
