//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carretilla_Angular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carretilla
    {
        public Carretilla()
        {
            this.detalleCarretilla = new HashSet<detalleCarretilla>();
        }
    
        public int idCarretilla { get; set; }
        public int totalProductos { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<detalleCarretilla> detalleCarretilla { get; set; }
    }
}
