//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carretilla_Angular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoriaProducto
    {
        public categoriaProducto()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int idCategoriaProducto { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
