//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carretilla_Angular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleCarretilla
    {
        public int idDetalleCarretilla { get; set; }
        public int idCarretilla { get; set; }
        public int idProducto { get; set; }
        public int Cantidad { get; set; }
        public bool Estado { get; set; }
    
        public virtual Carretilla Carretilla { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
