//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carretilla_Angular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.detalleCarretilla = new HashSet<detalleCarretilla>();
        }
    
        public int idProducto { get; set; }
        public int idCategoriaProducto { get; set; }
        public string Descripcion { get; set; }
        public double precioQuetzales { get; set; }
        public double precioDolares { get; set; }
        public int Existencia { get; set; }
        public bool enPromocion { get; set; }
        public bool Estado { get; set; }
        public string slug { get; set; }
    
        public virtual categoriaProducto categoriaProducto { get; set; }
        public virtual ICollection<detalleCarretilla> detalleCarretilla { get; set; }
    }
}
